Name: Manual Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The version to release.'
        required: true
        type: string
      isPrerelease:
        description: 'Wether this is a pre-release'
        required: true
        default: false
        type: boolean

jobs:
  build-and-release:
    name: 'Build and Release'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Install Node'
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: 'Install dependencies'
        run: npm ci
      - name: 'Build all Binaries'
        run: npm run build-exe-all
      - name: 'Release'
        uses: ncipollo/release-action@v1
        with:
          artifacts: 'bin/*'
          tag: V${{ inputs.version }}
          prerelease: ${{ inputs.isPrerelease }}
          commit: 'main'
  
